version: '3.9'
services:
  api:
    container_name: jawal_server
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: jawal_db
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    volumes:
      - jawa_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      
volumes:
  jawa_volume: