version: '3.9'
services:
  jawala_api:
    container_name: jawala_server
    build:
      context: .
      dockerfile: dockerfile.local
    ports:
      - 3000:3000
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
    depends_on:
      - jawala_db
  jawala_db:
    container_name: jawala_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - jawla_volume:/data/db
      
volumes:
  jawla_volume: {}